function ConvertSocialGeometryToObservations(DirList, dirlistpath, outputdir)
%usage: ConvertGeometryToObservations(DirList, outputdir)
% generate Observations data from DLC geometry, formatted for input to SSM
% redesigned Feb 2021 for the new camera data (replaces ConvertTracksToObservations)
% uses a DirList to load geometry outfiles from data directories
% concatenates some variables into a single matrix, and
% then saves as a mat file
% Expects a DirList created by DirListBuilder

X=[];
% groupdata=[];
if nargin==0,
    [DirList, dirlistpath] = uigetfile('*.txt', 'select DirList of data directories to scan');
    if isequal(DirList,0) || isequal(dirlistpath,0)
        fprintf('\ncancelled')
        return
    end
    outputdir=dirlistpath;
end
cd(dirlistpath)
fid=fopen(DirList);
i=0;
while 1 %processes until end of file is reached, then breaks
    line=fgetl(fid);
    if  ~ischar(line), break, end %break at end of file
    while isempty(line)
        line=fgetl(fid);
    end
    if strcmp(line, 'datadir')
        datadir=fgetl(fid);
        i=i+1;
        
        datadirs{i}=datadir;
        fprintf('\n%s', datadir)
        % adjust filenames to work on a mac
        if ismac datadir=macifypath(datadir);end
        cd(datadir)
        d=dir('geometry-*.mat');
        if isempty (d) %set to 1 to force re-process geometry
            ConvertSocialDLCtoGeometry(datadir)
            d=dir('geometry-*.mat');
        end
        geo_file=d(1).name;
        geo=load(geo_file);
        groupdata(i)=geo;
        numframes=geo.numframes;
        %mouse speed
        startidx=size(X,1)+1;
        X(startidx:startidx-1+numframes, 1)= geo.speed1;
        X(startidx:startidx-1+numframes, 2)= geo.speed2;
        X(startidx:startidx-1+numframes, 3)= geo.range;
        X(startidx:startidx-1+numframes, 4)= geo.drange;
        X(startidx:startidx-1+numframes, 5)= geo.RelativeAzimuth1;
        X(startidx:startidx-1+numframes, 6)= geo.RelativeAzimuth2;
        X(startidx:startidx-1+numframes, 7)= geo.mouse1velocity0;
        X(startidx:startidx-1+numframes, 8)= geo.mouse1velocity90;
        X(startidx:startidx-1+numframes, 9)= geo.mouse2velocity0;
        X(startidx:startidx-1+numframes, 10)= geo.mouse2velocity90;
        X(startidx:startidx-1+numframes, 11)= geo.mouse1_thigmo;
        X(startidx:startidx-1+numframes, 12)= geo.mouse2_thigmo;
        localframenum(startidx:startidx-1+numframes)=1:numframes;
        for k=startidx:startidx-1+numframes %kind of clunky, is it worth it?
            datadirs_by_frame{k}=datadir;
        end
        
    end
end



X_description{1}='mouse1speed';
X_description{2}='mouse2speed';
X_description{3}='range';
X_description{4}='drange';
X_description{5}='RelativeAzimuth1';
X_description{6}='RelativeAzimuth2';
X_description{7}='mouse1velocity0';
X_description{8}='mouse1velocity90';
X_description{9}='mouse2velocity0';
X_description{10}='mouse2velocity90';
X_description{11}='mouse1_thigmo';
X_description{12}='mouse2_thigmo';

X=real(X);

%normalize by z-score
rawX=X;
mu = nanmean(X);
sigma = nanstd(X);
sigma0 = sigma;
sigma0(sigma0==0) = 1;
X = (X-mu) ./ sigma0;

if sum(isnan(X(:)))> 10%length(X)
    error('nans during zscore')
end



%try downsampling to about 30Hz
decimate_factor=round(geo.framerate/40);
for i=1:size(X, 2)
    decX(:,i)=decimate(X(:,i), decimate_factor);
end
undecX=X;
X=decX;
fprintf('\ndecimated observations by %dx', decimate_factor)

cd(outputdir)
run_on=sprintf('generated by %s on %s', mfilename, datestr(now));
generated_by=mfilename;
framerate=geo.framerate;
save training_data X rawX X_description run_on DirList datadirs ...
    groupdata outputdir localframenum datadirs_by_frame ...
    decX decimate_factor undecX framerate
fprintf('\nsaved observations to file training_data.mat in %s', outputdir)

