function observation_subset(outputdir)
% create observations using a subset of training data
%overwrites training_data
cd(outputdir)
pwd

h=warndlg('you are about to overwrite training_data.mat, are you sure?' ,'overwrite?');
waitfor(h)

subset_idx=[3 4 5 6 ];

load training_data
save training_data_bak
fullrawX=rawX; %save original alongside the subset in training_data so we can plot tracks with it

% save training_data X rawX X_description run_on DirList datadirs ...
%     groupdata outputdir localframenum datadirs_by_frame ...
%     decX decimate_factor undecX framerate tracks tracks_description

% X_description{1}='mouse1speed';
% X_description{2}='mouse2speed';
% X_description{3}='range';
% X_description{4}='drange';
% X_description{5}='RelativeAzimuth1';
% X_description{6}='RelativeAzimuth2';
% X_description{7}='mouse1velocity0';
% X_description{8}='mouse1velocity90';
% X_description{9}='mouse2velocity0';
% X_description{10}='mouse2velocity90';
% X_description{11}='mouse1_thigmo';
% X_description{12}='mouse2_thigmo';


X_description=X_description(subset_idx);
X = X(:,subset_idx);
rawX = rawX(:,subset_idx);
decX = decX(:,subset_idx);
undecX = undecX(:,subset_idx);

run_on=sprintf('generated by %s on %s', mfilename, datestr(now));
generated_by=mfilename;

save training_data