function PlotEPM(datadir)
fprintf('\n%s',mfilename)
%usage: PlotEPM(datadir)
%loads a pruned_tpm generated by plot_posterior_probs
% plots the pattern of observations for each state
if nargin==0 datadir=pwd;end
cd(datadir)
load pruned_tpm
load training_data
%close all
fprintf('\nplotting emission probabilies for data in\n %s\n', pwd)

obs_dim=size(undecX, 2);
for i=1:pruned_num_states
    starts=pruned_epochs(i).starts;
    stops=pruned_epochs(i).stops;
    frames=[];
    for e=1:pruned_epochs(i).num_epochs
        frames=[frames starts(e):stops(e)];
    end
    mean_obs(i,:)=median(undecX(frames,:));
    std_obs(i,:)=std(undecX(frames,:));

%     %Add in Azimuth
%     sinazi=undecX(frames, find(contains(X_description, 'sinAzi')));
%     cosazi=undecX(frames, find(contains(X_description, 'cosAzi')));
%     azi=atan2(sinazi, cosazi);
%     mean_azi(i)=mean(azi);
end

mean_obs=mean_obs'; %flip
% mean_obs(end+1,:)=mean_azi;
% obs_dim=obs_dim+1;
% X_description{end+1}='Azimuth';

% normalize to the range 0,1
for j=1: obs_dim
    tmp=mean_obs(j,:) - mean(mean_obs(j,:)); %zero center
    nmean_obs(j,:)=tmp./std(tmp); %zscore
%    tmp=mean_obs(j,:) - min(mean_obs(j,:)); %make positive
%    nmean_obs(j,:)=tmp./max(tmp); %normalize
end

figure
imagesc(mean_obs)
xlabel('state')
ylabel('observation variable')
set(gca, 'ytick', 1:obs_dim);
set(gca, 'yticklabel', X_description);
title({'EPM, not normalized', datadir}, 'interpreter', 'none')

figure
imagesc(nmean_obs)
xlabel('state')
ylabel('observation variable')
set(gca, 'ytick', 1:obs_dim);
set(gca, 'yticklabel', X_description);
title('EPM, normalized by row ')
set(gca,'TickLabelInterpreter','none')


tree=linkage(tpm, 'average');
figure
colorthresh=.6*max(tree(:,3));
[H,T,outperm] = dendrogram(tree,'Orientation','left','ColorThreshold',colorthresh);
set(H,'LineWidth',2)
title('state clustering')
ylabel('state')

figure
imagesc(nmean_obs(:,outperm))
xlabel('state')
ylabel('observation variable')
set(gca, 'ytick', 1:obs_dim);
set(gca, 'yticklabel', X_description);
set(gca,'TickLabelInterpreter','none')
set(gca, 'xtick', 1:obs_dim);
set(gca, 'xticklabel', X_description);
set(gca, 'xtick',1:pruned_num_states,  'xticklabel', outperm)
title('EPM, normalized and clustered')
try colormap turbo
catch colormap jet
end
colorbar

figure
imagesc(mean_obs(:,outperm))
xlabel('state')
ylabel('observation variable')
set(gca, 'ytick', 1:obs_dim);
set(gca, 'yticklabel', X_description);
set(gca,'TickLabelInterpreter','none')
set(gca, 'xtick', 1:obs_dim);
set(gca, 'xticklabel', X_description);
set(gca, 'xtick',1:pruned_num_states,  'xticklabel', outperm)
title('EPM, clustered')
colorbar

figure
imagesc(mean_obs(:,outperm))
xlabel('state')
ylabel('observation variable')
set(gca, 'ytick', 1:obs_dim);
set(gca, 'yticklabel', X_description);
set(gca,'TickLabelInterpreter','none')
set(gca, 'xtick', 1:obs_dim);
set(gca, 'xticklabel', X_description);
set(gca, 'xtick',1:pruned_num_states,  'xticklabel', outperm)
title('EPM, clustered')
try colormap turbo
catch colormap jet
end
colorbar
try
    cl=clim;
    clim(max(abs(cl))*[-1 1])
catch
    cl=caxis;
    caxis(max(abs(cl))*[-1 1])
end

